# Site settings
title: Iran University of Science and Technology
course_name: Signals and Systems    
course_description: Course description.
course_semester: "Fall 2019"
description: |
    Instructor: Dr.MohammadReza Mohammadi
    

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://fatememirjalili2000.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://fatememirjalili2000.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: mrmohammadi@iust.ac.ir
twitter_username: 
github_username:  
authorurl:
google_scholar_page : https://scholar.google.com/citations?user=H34y7Q0AAAAJ&hl=en
personal_website:http: http://webpages.iust.ac.ir/mrmohammadi/index.html 
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
